[package]
name = "onelist"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.7.1"
axum = { version = "0.7.5" }
chrono = "0.4.38"
config = "0.14.0"

futures-util = "0.3.30"
mini-moka = "0.10.3"
onedrive-api = "0.10.0"
reqwest = { version = "0.12.4", features = ["json", "stream"] }
rust-embed = "8.3.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
snafu = "0.8.2"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.0"
